// <auto-generated />
using DiscordModeradorBot.Servicio.Infraestructura.Persistencia;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DiscordModeradorBot.Servicio.Infraestructura.Persistencia.Migraciones
{
    [DbContext(typeof(ContextoPersistencia))]
    [Migration("20260625150146_MIG0008NombreCanalMensajeAccionado")]
    partial class MIG0008NombreCanalMensajeAccionado
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("DiscordModeradorBot.Servicio.Infraestructura.Persistencia.Entidades.AccionEntidad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("DuracionTimeoutMinutos")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EventoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OrdenEjecucion")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RolObjetivo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("VentanaBorradoDias")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("EventoId", "OrdenEjecucion");

                    b.ToTable("Accion", (string)null);
                });

            modelBuilder.Entity("DiscordModeradorBot.Servicio.Infraestructura.Persistencia.Entidades.AdministradorEntidad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("CreadoEn")
                        .HasColumnType("INTEGER");

                    b.Property<string>("IdentificadorCuenta")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ResguardoPassword")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IdentificadorCuenta")
                        .IsUnique();

                    b.ToTable("Administrador", (string)null);
                });

            modelBuilder.Entity("DiscordModeradorBot.Servicio.Infraestructura.Persistencia.Entidades.CanalAfectadoEntidad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("IncidenteId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SnowflakeCanal")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IncidenteId");

                    b.ToTable("CanalAfectado", (string)null);
                });

            modelBuilder.Entity("DiscordModeradorBot.Servicio.Infraestructura.Persistencia.Entidades.EventoEntidad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Continuar")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Modo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ModoCombinacionGrupos")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Prioridad")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SnowflakeServidor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SnowflakeServidor", "Prioridad");

                    b.ToTable("Evento", (string)null);
                });

            modelBuilder.Entity("DiscordModeradorBot.Servicio.Infraestructura.Persistencia.Entidades.EventoGrupoEntidad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("EventoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GrupoDeReglasId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("EventoId");

                    b.ToTable("EventoGrupo", (string)null);
                });

            modelBuilder.Entity("DiscordModeradorBot.Servicio.Infraestructura.Persistencia.Entidades.ExencionEntidad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("SnowflakeServidor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SnowflakeSujeto")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TipoSujeto")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SnowflakeServidor");

                    b.HasIndex("SnowflakeServidor", "TipoSujeto", "SnowflakeSujeto")
                        .IsUnique();

                    b.ToTable("Exencion", (string)null);
                });

            modelBuilder.Entity("DiscordModeradorBot.Servicio.Infraestructura.Persistencia.Entidades.GrupoDeReglasEntidad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MinimoCoincidencias")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ModoCoincidencia")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SnowflakeServidor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SnowflakeServidor");

                    b.ToTable("GrupoDeReglas", (string)null);
                });

            modelBuilder.Entity("DiscordModeradorBot.Servicio.Infraestructura.Persistencia.Entidades.GrupoReglaEntidad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaseRegla")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaveReglaConducta")
                        .HasColumnType("TEXT");

                    b.Property<int>("GrupoDeReglasId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ReglaContenidoId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("GrupoDeReglasId");

                    b.ToTable("GrupoRegla", (string)null);
                });

            modelBuilder.Entity("DiscordModeradorBot.Servicio.Infraestructura.Persistencia.Entidades.IncidenteEntidad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Accion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("Instante")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Modo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NombrePolitica")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Resultado")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("ReversionAutorId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("ReversionFecha")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ServidorId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UsuarioId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ServidorId", "Instante");

                    b.ToTable("Incidente", (string)null);
                });

            modelBuilder.Entity("DiscordModeradorBot.Servicio.Infraestructura.Persistencia.Entidades.MensajeAccionadoEntidad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContenidoCopiado")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("IncidenteId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NombreCanal")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("");

                    b.Property<string>("SnowflakeCanal")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SnowflakeMensaje")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IncidenteId");

                    b.ToTable("MensajeAccionado", (string)null);
                });

            modelBuilder.Entity("DiscordModeradorBot.Servicio.Infraestructura.Persistencia.Entidades.ParametrosServidorEntidad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("SnowflakeServidor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("UmbralCanalesDistintos")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("VentanaAntirreboteSegundos")
                        .HasColumnType("REAL");

                    b.Property<double?>("VentanaDeteccionSegundos")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("SnowflakeServidor")
                        .IsUnique();

                    b.ToTable("ParametrosServidor", (string)null);
                });

            modelBuilder.Entity("DiscordModeradorBot.Servicio.Infraestructura.Persistencia.Entidades.ReglaContenidoEntidad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Criterio")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NombrePolitica")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("SensibleAMayusculas")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SnowflakeServidor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TipoCriterio")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SnowflakeServidor");

                    b.ToTable("Regla", (string)null);
                });

            modelBuilder.Entity("DiscordModeradorBot.Servicio.Infraestructura.Persistencia.Entidades.ServidorRegistradoEntidad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("CreadoEn")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EstadoActivacion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EstadoConexion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NombreDescriptivo")
                        .HasColumnType("TEXT");

                    b.Property<string>("PropositoCanalSalida")
                        .HasColumnType("TEXT");

                    b.Property<string>("SnowflakeCanalSalida")
                        .HasColumnType("TEXT");

                    b.Property<string>("SnowflakeServidor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TokenCifrado")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SnowflakeServidor")
                        .IsUnique();

                    b.ToTable("Servidor", (string)null);
                });

            modelBuilder.Entity("DiscordModeradorBot.Servicio.Infraestructura.Persistencia.Entidades.AccionEntidad", b =>
                {
                    b.HasOne("DiscordModeradorBot.Servicio.Infraestructura.Persistencia.Entidades.EventoEntidad", null)
                        .WithMany("Acciones")
                        .HasForeignKey("EventoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DiscordModeradorBot.Servicio.Infraestructura.Persistencia.Entidades.CanalAfectadoEntidad", b =>
                {
                    b.HasOne("DiscordModeradorBot.Servicio.Infraestructura.Persistencia.Entidades.IncidenteEntidad", null)
                        .WithMany("CanalesAfectados")
                        .HasForeignKey("IncidenteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DiscordModeradorBot.Servicio.Infraestructura.Persistencia.Entidades.EventoGrupoEntidad", b =>
                {
                    b.HasOne("DiscordModeradorBot.Servicio.Infraestructura.Persistencia.Entidades.EventoEntidad", null)
                        .WithMany("Grupos")
                        .HasForeignKey("EventoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DiscordModeradorBot.Servicio.Infraestructura.Persistencia.Entidades.GrupoReglaEntidad", b =>
                {
                    b.HasOne("DiscordModeradorBot.Servicio.Infraestructura.Persistencia.Entidades.GrupoDeReglasEntidad", null)
                        .WithMany("Reglas")
                        .HasForeignKey("GrupoDeReglasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DiscordModeradorBot.Servicio.Infraestructura.Persistencia.Entidades.MensajeAccionadoEntidad", b =>
                {
                    b.HasOne("DiscordModeradorBot.Servicio.Infraestructura.Persistencia.Entidades.IncidenteEntidad", null)
                        .WithMany("MensajesAccionados")
                        .HasForeignKey("IncidenteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DiscordModeradorBot.Servicio.Infraestructura.Persistencia.Entidades.EventoEntidad", b =>
                {
                    b.Navigation("Acciones");

                    b.Navigation("Grupos");
                });

            modelBuilder.Entity("DiscordModeradorBot.Servicio.Infraestructura.Persistencia.Entidades.GrupoDeReglasEntidad", b =>
                {
                    b.Navigation("Reglas");
                });

            modelBuilder.Entity("DiscordModeradorBot.Servicio.Infraestructura.Persistencia.Entidades.IncidenteEntidad", b =>
                {
                    b.Navigation("CanalesAfectados");

                    b.Navigation("MensajesAccionados");
                });
#pragma warning restore 612, 618
        }
    }
}
