// <auto-generated />
using DiscordModeradorBot.Servicio.Infraestructura.Persistencia;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DiscordModeradorBot.Servicio.Infraestructura.Persistencia.Migraciones
{
    [DbContext(typeof(ContextoPersistencia))]
    [Migration("20260621025154_MIG0001EsquemaInicial")]
    partial class MIG0001EsquemaInicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("DiscordModeradorBot.Servicio.Infraestructura.Persistencia.Entidades.IncidenteEntidad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Accion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CanalesAfectados")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CopiaMensajes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("Instante")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Modo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NombrePolitica")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Resultado")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ServidorId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UsuarioId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ServidorId", "Instante");

                    b.ToTable("Incidente", (string)null);
                });

            modelBuilder.Entity("DiscordModeradorBot.Servicio.Infraestructura.Persistencia.Entidades.ServidorRegistradoEntidad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("CreadoEn")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EstadoActivacion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EstadoConexion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NombreDescriptivo")
                        .HasColumnType("TEXT");

                    b.Property<string>("SnowflakeServidor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TokenCifrado")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SnowflakeServidor")
                        .IsUnique();

                    b.ToTable("Servidor", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
