// <auto-generated />
using DiscordModeradorBot.Servicio.Infraestructura.Persistencia;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DiscordModeradorBot.Servicio.Infraestructura.Persistencia.Migraciones
{
    [DbContext(typeof(ContextoPersistencia))]
    [Migration("20260621125851_MIG0003ReglaContenido")]
    partial class MIG0003ReglaContenido
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("DiscordModeradorBot.Servicio.Infraestructura.Persistencia.Entidades.CanalAfectadoEntidad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("IncidenteId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SnowflakeCanal")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IncidenteId");

                    b.ToTable("CanalAfectado", (string)null);
                });

            modelBuilder.Entity("DiscordModeradorBot.Servicio.Infraestructura.Persistencia.Entidades.IncidenteEntidad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Accion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("Instante")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Modo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NombrePolitica")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Resultado")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ServidorId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UsuarioId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ServidorId", "Instante");

                    b.ToTable("Incidente", (string)null);
                });

            modelBuilder.Entity("DiscordModeradorBot.Servicio.Infraestructura.Persistencia.Entidades.MensajeAccionadoEntidad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContenidoCopiado")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("IncidenteId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SnowflakeCanal")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SnowflakeMensaje")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IncidenteId");

                    b.ToTable("MensajeAccionado", (string)null);
                });

            modelBuilder.Entity("DiscordModeradorBot.Servicio.Infraestructura.Persistencia.Entidades.ReglaContenidoEntidad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Criterio")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NombrePolitica")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("SensibleAMayusculas")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SnowflakeServidor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TipoCriterio")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SnowflakeServidor");

                    b.ToTable("Regla", (string)null);
                });

            modelBuilder.Entity("DiscordModeradorBot.Servicio.Infraestructura.Persistencia.Entidades.ServidorRegistradoEntidad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("CreadoEn")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EstadoActivacion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EstadoConexion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NombreDescriptivo")
                        .HasColumnType("TEXT");

                    b.Property<string>("PropositoCanalSalida")
                        .HasColumnType("TEXT");

                    b.Property<string>("SnowflakeCanalSalida")
                        .HasColumnType("TEXT");

                    b.Property<string>("SnowflakeServidor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TokenCifrado")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SnowflakeServidor")
                        .IsUnique();

                    b.ToTable("Servidor", (string)null);
                });

            modelBuilder.Entity("DiscordModeradorBot.Servicio.Infraestructura.Persistencia.Entidades.CanalAfectadoEntidad", b =>
                {
                    b.HasOne("DiscordModeradorBot.Servicio.Infraestructura.Persistencia.Entidades.IncidenteEntidad", null)
                        .WithMany("CanalesAfectados")
                        .HasForeignKey("IncidenteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DiscordModeradorBot.Servicio.Infraestructura.Persistencia.Entidades.MensajeAccionadoEntidad", b =>
                {
                    b.HasOne("DiscordModeradorBot.Servicio.Infraestructura.Persistencia.Entidades.IncidenteEntidad", null)
                        .WithMany("MensajesAccionados")
                        .HasForeignKey("IncidenteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DiscordModeradorBot.Servicio.Infraestructura.Persistencia.Entidades.IncidenteEntidad", b =>
                {
                    b.Navigation("CanalesAfectados");

                    b.Navigation("MensajesAccionados");
                });
#pragma warning restore 612, 618
        }
    }
}
